#!/usr/bin/env bash

export COLOR_NC='\033[0m'
export COLOR_RED='\033[0;31m'
export COLOR_GREEN='\033[0;32m'

DOT="$PWD/../scripts/dotfile"

while IFS= read -r -d '' dir; do
  dir=$(dirname "$dir")
  echo -e "${COLOR_GREEN}Processing directory: $dir${COLOR_NC}"
  pushd "$dir" > /dev/null
  "$DOT" link
  popd > /dev/null
done < <(find "." -name "dotlist" -print0)
