version: '3'

silent: false

tasks:
  default:
    - task: link

  link:
    - for:
        var: DIRS
      cmd: cd "{{ .ITEM }}" && task link

  unlink:
    - for:
        var: DIRS
      cmd: cd "{{ .ITEM }}" && task unlink

vars:
  DIRS:
    sh: echo "$(ls -d */)"
