version: '3'

silent: true

includes:
  lib:
    taskfile: ./lib.yml

  server:
    taskfile: ./server.yml
    flatten: true

tasks:
  default:
    desc: "Run update_dicts"
    aliases: [list]
    cmds:
      - task --list

  update_dicts:
    desc: "Update the dicts, and combine them to yaskkserv2 dictionary"
    deps:
      - install_deps
    cmds:
      - mkdir -p "{{ .OUTPUT_DIR }}"
      - mkdir -p "{{ .TMP_DIR }}"
      - defer: rm -rf "{{ .TMP_DIR }}"
      - task: download_all
      - task: gen_skk_dict
        vars:
          DICT_FILES: "{{ range $idx, $item := .DICTS }}
            {{ $.TMP_DIR }}/{{ osBase $item }}{{ if not (hasSuffix \".utf8\" $item) }}.utf8{{ end }}
          {{ end }}"
          DST_FILE: "{{ .SKK_FILE }}"
      - task: gen_yaskkserv2_dict
        vars:
          SKK_FILE: "{{ .SKK_FILE }}"
          SERVER_DICT_FILE: "{{ .SERVER_DICT_FILE }}"
    vars:
      TMP_DIR: "./tmp"

  clean:
    desc: "Remove dict fils"
    cmds:
      - rm -rf "{{ .OUTPUT_DIR }}"

  download_all:
    internal: true
    requires:
      vars: [ DICTS ]
    cmds:
      - for:
          var: DICTS
        task: lib:download_dict
        vars:
          TMP_DIR: "{{ .TMP_DIR }}"
          URL: "{{ .ITEM }}"

  gen_skk_dict:
    internal: true
    requires:
      vars: [ DICT_FILES, DST_FILE ]
    cmds:
      - echo "Generating {{ .DST_FILE | osBase }}"
      - 'echo ";; -*- mode: fundamental; coding: utf-8 -*-" > "{{ .DST_FILE }}"'
      - skkdic-expr2 {{ .DICT_FILES }} >> "{{ .DST_FILE }}"

  restore_user_dict:
    desc: "Backup macSKK user dictionary"
    cmds:
      - age -d -o ~/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Dictionaries/skk-jisyo.utf8 "{{ .PWD }}/files/skk-jisyo.utf8" 
  backup_user_dict:
    desc: "Restore macSKK user dictionary"
    cmds:
      - age -p -o "{{ .PWD }}/files/skk-jisyo.utf8" ~/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Dictionaries/skk-jisyo.utf8

  install_deps:
    internal: true
    run: once
    cmds:
      - command -v skkdic-expr2 > /dev/null || brew install skktools
      - command -v yaskkserv2 > /dev/null || (brew tap waynezhang/tap && brew install --HEAD yaskkserv2)
      - command -v age > /dev/null || brew install age

vars:
  DICTS:
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.L" # 基本辞書
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.jinmei" # 人名、特に日本人の姓名
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.geo" # 日本郵便株式会社データ
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.propernoun" # 芸能・音楽・企業・アニメなど
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.station" # 駅名・路線名・鉄道会社名およびその他の鉄道用語の専門辞書
    # プラス
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.fullname" # 人名録。姓と名に分離したものは SKK-JISYO.jinmei に
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.law" # 法律用語電子化辞書
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.okinawa" # 沖縄辞書
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.china_taiwan" # 中国、台湾の地名
    # 特殊変換
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.assoc" # 見出し語と候補との間に一定の連想関係があるエントリ。大量の略語を含んでいる。
    # 特殊
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.JIS2" # JIS 第二水準の文字
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.JIS3_4" # JIS 第三、第四水準の文字
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.JIS2004" # JIS X 0213 の 2004 年改正で追加された「表外漢字 UCS 互換」10 文字
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.itaiji" # 異体字変換
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.itaiji.JIS3_4" # itaiji の JIS 第３・第４水準版
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.mazegaki" # 交ぜ書き
    # 編纂
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.wrong.annotated" # 間違えて含まれていたエントリ
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/SKK-JISYO.edict" # abbrev
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/zipcode/SKK-JISYO.zipcode"
    - "https://github.com/skk-dev/dict/raw/refs/heads/master/zipcode/SKK-JISYO.office.zipcode"
    # その他
    - "https://github.com/uasi/skk-emoji-jisyo/raw/refs/heads/master/SKK-JISYO.emoji.utf8" # emoji
  OUTPUT_DIR:
    sh: echo "$(pwd)/.build"
  SKK_FILE: "{{ .OUTPUT_DIR }}/SKK-JISYO.combined.utf8"
  SERVER_DICT_FILE: "{{ .OUTPUT_DIR }}/yaskkserv2-dict"
