version: '3'

silent: false

tasks:
  default:
    - task: link

  link:
    cmds:
      - ln -s "{{ .PWD }}/files/starship.toml" {{ .TARGET }}

  unlink:
    cmds:
      - rm "{{ .TARGET }}"

vars:
  TARGET: "{{ .HOME }}/.config/starship.toml"
