version: '3'

silent: false

tasks:
  default:
    - task: link

  link:
    cmds:
      - ln -s "{{ .PWD }}/files" "{{ .TARGET }}"

  unlink:
    cmds:
      - rm -rf "{{ .TARGET }}"

vars:
  TARGET: "{{ .HOME }}/Library/Application\ Support/com.mitchellh.ghostty"
