version: '3'

silent: false

tasks:
  default:
    - task: link

  link:
    cmds:
      - ln -s "{{ .PWD }}/files" {{ .TARGET }}

  unlink:
    cmds:
      - rm "{{ .TARGET }}"

vars:
  TARGET: "{{ .HOME }}/.hammerspoon"
